---
version: '3.9'

services:
  readthedocs:
    image: sv-equinox/docs:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - docs
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.docs-demo.rule: Host(`docs-demo.svequinox.nl`)
      traefik.http.routers.docs-demo.entrypoints: https, http
      traefik.http.services.docs-demo.loadbalancer.server.port: 80
      traefik.http.routers.docs-demo.tls: true
      traefik.http.routers.docs-demo.tls.certresolver: production

networks:
  docs:
    name: docs-demo
  traefik:
    external: true
